version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: source/conf.py
  source: source  # Correct way to specify the source directory for Sphinx
  requirements: requirements.txt

formats:
  - pdf

python:
  install:
    - requirements: requirements.txt