version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  source_dir: source # Or your source directory if different

sphinx:
  configuration: source/conf.py
  requirements: requirements.txt # Or your requirements file path

formats:
  - pdf

python:
  install:
    - requirements: requirements.txt  # Correct: Now a list with one dictionary item